# Author: Denis A. Engemann, email: denis.engemann@gmail.com
#
# License: BSD (3-clause)


class Bunch(dict):
    """ Dict that exposes keys as attributes """
    def __init__(self, *args, **kwargs):
        dict.__init__(self, *args, **kwargs)
        self.__dict__ = self


PMD = Bunch()

PMD.PT_ARTICLE      = 'journal article'
PMD.DEF_FIELDS      = ['TI', 'AU', 'DP', 'AB', 'JT', 'TA', 'PT', 'MH', 'PMID']
PMD.SEP_PAGES_ENTRY = ';'
PMD.AGES_RANGE      = '-'
PMD.AB              = 'Abstract'
PMD.CI              = 'Copyright Information'
PMD.AD              = 'Affiliation'
PMD.IRAD            = 'Investigator Affiliation'
PMD.AID             = 'Article Identifier'
PMD.AU              = 'Author'
PMD.FAU             = 'Full Author'
PMD.CN              = 'Corporate Author'
PMD.DCOM            = 'Date Completed'
PMD.DA              = 'Date Created'
PMD.LR              = 'Date Last Revised'
PMD.DEP             = 'Date of Electronic Publication'
PMD.DP              = 'Date of Publication'
PMD.EDAT            = 'Entrez Date'
PMD.GS              = 'Gene Symbol'
PMD.GN              = 'General Note'
PMD.GR              = 'Grant Number'
PMD.IR              = 'Investigator Name'
PMD.FIR             = 'Full Investigator Name'
PMD.IS              = 'ISSN'
PMD.IP              = 'Issue'
PMD.TA              = 'Journal Title Abbreviation'
PMD.JT              = 'Journal Title'
PMD.LA              = 'Language'
PMD.LID             = 'Location Identifier'
PMD.MID             = 'Manuscript Identifier'
PMD.MHDA            = 'MeSH Date'
PMD.MH              = 'MeSH Terms'
PMD.JID             = 'NLM Unique ID'
PMD.RF              = 'Number of References'
PMD.OAB             = 'Other Abstract'
PMD.OCI             = 'Other Copyright Information'
PMD.OID             = 'Other ID'
PMD.OT              = 'Other Term'
PMD.OTO             = 'Other Term Owner'
PMD.OWN             = 'Owner'
PMD.PG              = 'Pagination'
PMD.PS              = 'Personal Name as Subject'
PMD.FPS             = 'Full Personal Name as Subject'
PMD.PL              = 'Place of Publication'
PMD.PHST            = 'Publication History Status'
PMD.PST             = 'Publication Status'
PMD.PT              = 'Publication Type'
PMD.PUBM            = 'Publishing Model'
PMD.PMC             = 'PubMed Central Identifier'
PMD.PMID            = 'PubMed Unique Identifier'
PMD.RN              = 'Registry Number/EC Number'
PMD.NM              = 'Substance Name'
PMD.SI              = 'Secondary Source ID'
PMD.SO              = 'Source'
PMD.SFM             = 'Space Flight Mission'
PMD.STAT            = 'Status'
PMD.SB              = 'Subset'
PMD.TI              = 'Title'
PMD.TT              = 'Transliterated Title'
PMD.VI              = 'Volume'
PMD.CON             = 'Comment on'
PMD.CIN             = 'Comment in'
PMD.EIN             = 'Erratum in'
PMD.EFR             = 'Erratum for'
PMD.CRI             = 'Corrected and Republished in'
PMD.CRF             = 'Corrected and Republished from'
PMD.PRIN            = 'Partial retraction in'
PMD.PROF            = 'Partial retraction of'
PMD.RPI             = 'Republished in'
PMD.RPF             = 'Republished from'
PMD.RIN             = 'Retraction in'
PMD.ROF             = 'Retraction of'
PMD.UIN             = 'Update in'
PMD.UOF             = 'Update of'
PMD.SPIN            = 'Summary for patient'
PMD.ORI             = 'Original report'